#!/bin/bash

alias ll="ls -l"
alias lo="ls -o"
alias lh="ls -lh"
alias la="ls -la"
alias ls-la="ls -la" 
alias sl="ls"
alias l="ls"
alias s="ls"

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."